FROM python:3

WORKDIR /usr/src/app

COPY . .
RUN chmod +x entrypoint.sh

RUN apt-get -y update
RUN pip3 install -r requirements.txt
RUN apt-get update && apt-get install -y netcat

EXPOSE ${FLASK_CONTAINER_PORT}

ENTRYPOINT ["bash","entrypoint.sh"]
